### ISSUE TITLE
Many issues with elasticsearch 6.3.0 in

### ISSUE THREAD

**Issue by dacr** [dlumbrer/kbn_radar#4]
I've tested your plugin with 6.2.x release and it's working fine, but with the new elasticsearch 6.3 release, your plugin (6.3.X-0 /  0a28f38) is generating many issues within kibana user interface, not usable at all :(

![image](https://user-images.githubusercontent.com/381901/42519904-514547c6-8465-11e8-8aa9-a59148dd25e2.png)

**Comment by dacr** [comment]
same problem with elasticsearch/kibana 6.3.1, I've only tested your plugin through the release you've published, and looks it a little bit old, as it was released on "5, Mar"

**Comment by dlumbrer** [comment]
I've just tested the release and it works in Kibana 6.3.1 and 6.3.0, did you download the plugin throught the zip/tar of the release or cloning the repository'

**Comment by dacr** [comment]
I've downloaded it from the .tar.gz file

**Comment by dlumbrer** [comment]
Installing it via cloning the respository it works great, there was an error with the binaries of the release, I just updated it. Sorry!
