### ISSUE TITLE
 Cannot read property 'displayName' using Sum Bucket

### ISSUE THREAD

**Issue by alpgarcia** [dlumbrer/kbn_radar#7]
Please see attached screenshot. With this configuration, I got:
```
TypeError: Cannot read property 'displayName' of undefined
```

![captura de pantalla de 2019-01-11 13-09-41](https://user-images.githubusercontent.com/3502941/51033009-3d5e8280-15a2-11e9-8f2f-73b94ef66202.png)

**Comment by dlumbrer** [comment]
I'm going to work on this, thanks
